// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/notification.go

// Package mock_notification is a generated GoMock package.
package mock_notification

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	notification "github.com/ispec-inc/bewin-monorepo/admin/pkg/notification"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockPublisher) Send(input notification.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockPublisherMockRecorder) Send(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockPublisher)(nil).Send), input)
}
