apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification
  title: high testability notification service
  annotations:
    github.com/project-slug: ispec-inc/notification
    backstage.io/techdocs-ref: dir:./
  description: |
  tags:
    - golang
    - notification
spec:
  type: library
  owner: yamad07
  lifecycle: experimental
  providesApis:
    - bewin-admin
